server/db/models/product.js
Please complete review of first draft of product model. I think we still need to decide on whether certain categories should be fields on the product model itself (e.g., sizes available, color, gender, etc.). In my view, this is highly dependent on what kinds of products we want to sell. Probably worth a team discussion. I think this is fine for us to proceed with creating routes, but we should decide this sooner rather than later.
=> first draft of product model

package-lock.json, server/db/models/user.js
Created the User Model with the appropriate fields (previously discussed). I must note that the boilerplate base code that we used as our starting point already had a user.js file for the User model. Erika and I verified that we were going to keep the existing fields and then added the missing fields we had discussed during the model brainstorming.
=> Created User model

seed.js
-- wrote first draft of seed file
-- please review entire file
=> first draft of seed file

server/db/models/index.js
Please review the associations for the models for the db index
=> added associations in models/index

server/db/models/cart.js
=> Created Cart model

server/db/models/order.js
=> Created Order Model

package.json, seed.js, server/api/users.js, server/db/db.js, server/db/models/index.js, server/db/models/order.js, server/db/models/user.js
seed code still needs some hard-coded info, but otherwise is working
=> working seed file and association updates

package.json, server/api/index.js, server/api/orders.js, server/api/users.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/order.js, server/db/models/product.js, tests/user.spec.js, tests/users.spec.js
Created tests folder and added backend tests to the folder. Some front end tests still in modular folders.
=> Tests folder

server/api/index.js, server/api/orders.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/order.js, server/db/models/product.js
Routes have been tested with postman. All are working except userId/orders.
=> User and order routes

package-lock.json, seed.js, server/api/carts.js, server/api/categories.js, server/api/index.js, server/db/models/index.js
=> category model is finished

package.json, seed.js, tests/product.spec.js, tests/user.spec.js, tests/users.spec.js
=> Users tests

server/db/index.js, server/db/models/product.js, server/db/testing-db.js, tests/product_model.spec.js
Wrote a short test file that tests the validations of the product models.
=> Product model tests

server/api/categories.js, tests/cart.spec.js, tests/carts.spec.js, tests/categories.spec.js, tests/category.spec.js
test specs for
.category route
.category model
. cart route
.cart model
is written
=> test models and routes of category and cart are completed

server/api/index.js
=> fix products route typo

server/api/carts.js, server/api/categories.js, server/api/products.js, server/api/users.js
small changes to styling of routes for consistent code style
=> Small changes to all api routes

seed.js, server/db/models/category.js
added some categories to the seed file and updated the model
=> model changes to categories and seed

seed.js, server/db/models/index.js, server/db/models/product.js, server/db/models/review.js
=> some model cahnges are implemented

comments.md
=> comments from CR1 added

seed.js, server/api/carts.js, server/api/index.js, server/api/orders.js, server/db/models/cart.js, server/db/models/category.js, server/db/models/index.js, server/db/models/order.js, server/db/models/photo.js, server/db/models/product.js, tests/cart.spec.js, tests/carts.spec.js, tests/product_model.spec.js
Added instance method: for checking the product stock availability, set availability to false or true
Added review model with two fields: 1) text and 2) five-star rating
Added associations: (associated with User via above and with Product -- Product.hasMany(Review), Review.belongsTo(Product))
Added new photo model with field imageURL and associations
Added categories to the seed file
Deleted cart model
=> Leftover model changes

client/store/products.js, tests/redux_store.spec.js
=> created redux-tests

seed.js, server/db/models/index.js, server/db/models/order.js
=> change in order model

server/api/products.js, server/api/users.js, server/db/models/index.js, server/db/models/orderProduct.js
=> Product model join table

server/api/orders.js
=> corrected small error Purchase instead of Product in orders router

server/api/orders.js, server/db/models/index.js, server/db/models/product.js
=> Testing models

seed.js, server/api/categories.js, server/api/orders.js, server/api/products.js, server/api/users.js
=> http statuses are added

client/components/Navbar.jsx, client/store/auth.js, client/store/index.js, package-lock.json, package.json, server/auth/google.js, server/auth/index.js, server/auth/local.js, server/db/models/orderProduct.js
- added decrement and increment quantity functions as instance methods on the OrderProduct model
Sazi - I'm not sure why the Navbar component changes are also showing up in this request. I pushed them for review from a different branch.
=> OrderProduct model

server/auth/google.js, server/auth/index.js, server/auth/local.js
Made small changes to authentication routes provided in boilerplate code, mostly cleaning up comments, and isolating a few variables re: auther workshop. Probably not necessary to closely review this code, as these changes were minor.
=> authentication routes

client/store/auth.js, server/auth/google.js, server/auth/index.js, server/auth/local.js
- created authentication reducer
- created action types, action creators, and thunk creators
- based closely on auther workshop, with attention paid to changes made to authentication routes on the current project
=> create auth reducer

client/components/Navbar.jsx, client/store/auth.js, server/auth/google.js, server/auth/index.js, server/auth/local.js
- created first draft of navbar component which conditionally renders either Signup/Login or Logout based on current user id; currently throwing an error, because there is no current user on state -- this can't be fixed until we fetch initial data at the root
=> create first draft navbar component

server/db/models/index.js, server/db/models/order.js, server/db/models/product.js
=> model-changes are finished

server/api/orderProducts.js, server/db/models/index.js, server/db/models/orderProduct.js
- created new orderProducts router with three routes to edit amount of items in order and to delete item from order
- also made small change to orderProduct model to correct earlier mistake i made in naming in instance method
- also added orderProduct model to index.js file in db/models
=> created new orderProducts router

client/components/Products.jsx, client/components/Root.jsx, client/components/Sidebar.jsx, client/store/categories.js, client/store/chosenCategory.js, client/store/index.js
=> Products reducer links

client/components/SingleProduct.jsx, client/store/cart.js, client/store/order.js, server/api/index.js, server/api/orderProducts.js, server/db/models/index.js
created cart component and added post route to orderProduct route files
=> cart component is written

client/components/Checkout.jsx
=> corrected two small syntax errors in Checkout component

package.json
=> fixed file changes and package.json to match deployment specs

client/components/Login.jsx, client/components/Root.jsx
=> changes to Login and Root

client/components/Cart.jsx, client/components/Navbar.jsx, client/components/Products.jsx, client/components/Root.jsx, client/components/SingleProduct.jsx, client/store/cart.js, client/store/categories.js, client/store/chosenCategory.js, client/store/chosenProduct.js, client/store/currentOrder.js, client/store/products.js, package-lock.json, public/bootstrap.css, server/api/index.js, server/api/orderProducts.js, server/api/products.js
=> Cart functionality

client/components/Root.jsx, client/components/Sidebar.jsx, public/index.html, public/style.css
=> Changing sidebar style

client/components/Cart.jsx, client/components/Checkout.jsx, client/components/Products.jsx, client/components/SingleProduct.jsx, public/style.css
General fixes to styling and image rendering
=> Styling fixes

client/components/Home.jsx, client/components/Navbar.jsx, client/components/Products.jsx, client/store/search.js
=> search page is ready and functionality is done

client/components/AdminPanel.jsx, client/components/Checkout.jsx, client/components/Root.jsx
=> (FIX) Fix conflicts and comment out adminpanel

client/components/MyStoreCheckout.jsx, client/components/Root.jsx
=> fixing checkout layout

client/store/currentOrder.js
=> updating checkout to check for user id

client/components/Login.jsx, client/components/Products.jsx, client/components/SingleProduct.jsx
=> Morning of

client/components/SingleProduct.jsx
=> (STYLING) add toast to singleproduct on add to cart
